### PR TITLE
Generate MFG Files: OH2A1A1-1 - ASSY, LOWER INSTRUMENT PANEL STRUCTURE

### LINKED ISSUE #747: Generate MFG Files: OH2A1A1-1 - ASSY, LOWER INSTRUMENT PANEL STRUCTURE
Generate the manufacturing files for Generate MFG Files: OH2A1A1-1 - ASSY, LOWER INSTRUMENT PANEL STRUCTURE. 

__Check off each item in issue as you complete it.__

### File generation
- [OH Wiki HOWTO Link](https://github.com/jrsteensen/OpenHornet/wiki/HOWTO:-Generating-Fusion360-Manufacturing-Files)
- [ ] Generate SVG files (if required.)
- [ ] Generate 3MF files (if required.)
- [ ] Generate STEP files (if required.)
- [ ] Copy the relevant decal PDFs from the art folder to the relevant manufacturing folder (if required.)
### Review your files
- [ ] Verify against drawing parts list that all the relevant manufacturing files have been created.
- [ ] Open each SVG in your browser and compare against part to ensure it appears the same and its filename is correct.
- [ ] Open each 3MF in a slicer of your choice and verify geometry matches F360 model and its filename is correct.
- [ ] Open each STEP in a STEP file viewer of your choice and verify geometry matches F360 model and its filename is correct.
### Submit your files
- [ ] Create a github PR against the beta 1 branch with the manufacturing files located in correct location of the release folder.
- [ ] Request a review of the PR.

#### Why a PR?
It gives you credit when I generate the changelog in the release, and (more importantly) adds traceability to the history of the issues.

### PR DESCRIPTION
**Pull request by eHanseJoerg**
# Description

Initial commit for the Lower Isntrument Panel Structure (LIP), issue #747 . Generated one SVG file for the mount of the UIP on the LIP.

## Addresses 

Close #747 

## File generation
 [OH Wiki HOWTO Link](https://github.com/jrsteensen/OpenHornet/wiki/HOWTO:-Generating-Fusion360-Manufacturing-Files)
 
 * [X]  Generate SVG files (if required.)
 * [X]  Generate 3MF files (if required.)
 * [-]  Generate STEP files (if required.)
 * [-]  Copy the relevant decal PDFs from the art folder to the relevant manufacturing folder (if required.)
 
 ## Review your files
 * [X]  Verify against drawing parts list that all the relevant manufacturing files have been created.
 * [X]  Open each SVG in your browser and compare against part to ensure it appears the same and its filename is correct.
 * [X]  Open each 3MF in a slicer of your choice and verify geometry matches F360 model and its filename is correct.
 * [-]  Open each STEP in a STEP file viewer of your choice and verify geometry matches F360 model and its filename is correct.
 
 ## Submit your files
 * [X]  Create a github PR against the beta 1 branch with the manufacturing files located in correct location of the release folder.
 * [X]  Request a review of the PR.

### CODE REVIEW

**Comment by eHanseJoerg** [comment]
Also kindly check if file name convention is met.

**Comment by eHanseJoerg** [comment]
Will do!

**Comment by eHanseJoerg** [comment]
All SVG and 3MF files generated. Kindly check @jrsteensen

**Review by jrsteensen — CHANGES_REQUESTED** [review]
- [ ] Move all manufacturing files into a folder called "Manufacturing" in the LIP Structure assembly.

**Comment by eHanseJoerg** [comment]
Moved to Manuf folder.

**Review by jrsteensen — APPROVED** [review]

**Pull request merged**
