### PR TITLE
I2C Rerouting

### PR DESCRIPTION
**Pull request by balzreber**
# Description

Rerouted I2C from Pin D4/D5 to A4/A5. Had to tear up some stuff. Therefore good verification needed.

Addresses #164 

## Type of change
- [x] Change ECAD (fixed issue with existing PCB)
- [x] Bug fix (non-breaking change which fixes an issue)

## PCB/ECAD:
- [x] PCB routed

### CODE REVIEW

**Comment by MrMagicMan** [comment]
Checked the changes you made on the Schematic, it looks good.

The I2C changes for the PCB look good too, 

I have some suggestions for the layout that I know are not things you changed.

Suggestions:

- [ ] Make the power traces larger, right now they are ~9 mills, this is good for around a 400-500mA  current with a 10C rise (here a calculator if your interested https://www.4pcb.com/trace-width-calculator.html) Also right now there is no fuse, so with a short there is a risk that the trace will sacrifice itself, if the traces are larger then there is less risk of this.. 

- [ ] Not as important but make all the traces larger, with crappy manufactures (read cheap) then sometimes they do not hold the same tolerances, the larger the trace the less of an issue you can have if they over-etch the boards. 

- [ ] Ground is not well connected across the nano, If you look closely there is only ground connections from the plane through the actual ground pins and a little sliver up top, but it does not go between the pins in the dip package, it may be worthwhile to adjust the spacing requirements so that ground flows between these pads and creates a more uniform ground plane.
Now from the board edge 20 mills is good but you should not need the same clearance around the components.

- [ ] Similarly add some ground via stitching (ground to ground vias) to connect the bottom ground plane and the top ground plane, there are some islands of ground that are not 

Much smaller things:

- [ ] No mounting holes on the design, this just means we need a custom holder or double sided tape to hold this on.

- [ ] Missing OH logo?

- [ ] Could use some silkscreen labels on for example J6 and J8

Thoughts:
@amanuense 
@jrsteensen

**Comment by MrMagicMan** [comment]
@jrsteensen looks like its up to you to merge, 
@balzreber it is stating merging is blocked because it requires a signed commit, have you tried adding a GPG key to your git?

**Comment by jrsteensen** [comment]
@balzreber Are there any more pending changes to this PCB?

**Comment by balzreber** [comment]
I just saw that the OH Logo has vanished from the Board. Can someone please check if that is a local problem with me or if this occurs with everyone? I also would like to write the name of the Board on it. Otherwise, we should be good.

**Comment by jrsteensen** [comment]
@balzreber It appears its an issue - doesn't show up on mine either.

**Comment by jrsteensen** [comment]
Should this be incrementally merged?

**Comment by jrsteensen** [comment]
This was addressed in the ABSIS redesign. I am closing this PR.

**Pull request closed without merging**
