### PR TITLE
ECAD Directory Overhaul

### PR DESCRIPTION
**Pull request by Exprezz0**
# Description

Initial Pull Request for ECAD update and overhaul.  Current objectives for the update are as follows:

- [x] Establish ReadMe file specifically for ECAD directory to facilitate the following:
   - [x] 1:  Navigate the ECAD file structure
   - [x] 2:  ~~Proper Installation of KiCAD 6.0 for new users~~ Moved to separate, detailed document (Installation.md), but need to reference and summarize within this ReadMe.
   - [x] 3:  ~~How to migrate older versions of PCB's made in KiCAD 5.x.x to KiCAD 6.0 as well as their libraries~~ No longer required.
  
- [x] ECAD Transition - (Tasks are being conducted in parallel with each other; beginning with backlit PCBs)
   - [x] Migrate ECAD files from KiKAD 5.x.x to KiCAD 6.0
      - [x] Backlight PCB
      - [x] Functional
      - [x] ABSIS
   - [x] Reorganize ECAD File Structure based on OH Requirements
   - [x] Cleanup excess files within the ECAD directory that are obsolete
   - [x] Generate JLCPCB manufacturing files with updated components or alternatives (BOM/Pick & Place)

--------------------------
### First commit is the ReadMe file to establish the basis for the Pull Request. 
In it's current state, the readme is a rough draft and will constantly be updated as the aforementioned is completed and based on additional guidance.  It currently consists of a _potential_ file structure and a little information on the PCB Manufacturing progress.

### CODE REVIEW

**Comment by jrsteensen** [comment]
Very small tweak to the order of the updates - migrate to 6.0 first after making the readme/manufacturing readme.

The directory update/reorg shouldn't be much from the layout now at the PCB folder - Manufacturing folders should consist of a folder of gerbers, a zip of that folder, then the pick and place/SMD BOM and ideally a second thru hole BOM. The goal would be to be able to roll those up easily into a master BOM.

**Comment by Exprezz0** [comment]
Update on Transition:  

I think it's important to note the following, especially given the latest commits and changes to the file structure.  Since KiCad 6 now embeds the library information within the schematic and pcb itself, changing the file structure has zero affect on any projects.  There are currently symbols and footprints within these documents that are populated despite the file path being non-existent for quite some time.  For example:  The APU Panel has been transitioned to KiCad 6.  _The "OH" logo footprint's original path has not altered in anyway, but the graphic still populates despite belonging to a library that doesn't exist.  See below:_

image

[Taken from KiCad 6 Documentation - Here](https://docs.kicad.org/master/en/kicad/kicad.html#kicad_files_and_folders)
> Storing and and sending KiCad files
> 
> KiCad schematic and board files contain all the schematic symbols and footprints used in the design, so you can back up or send these files by themselves with no issue. Some important design information is stored in the project file (.kicad_pro), so if you are sending a complete design, make sure to include it.

With this being said, I think we can safety move forward without any issues.  I've tested this on a cloned ECAD branch to make sure everything would work out before making adjustments to the Beta-1 branch, and did not have any conflicts.

**Comment by Exprezz0** [comment]
Backlight PCB's are complete with the transition to KiCad 6.  
1:  All excess files have been removed, JLCPCB manufacturing files have been created based on @jrsteensen guidance here (https://github.com/jrsteensen/OpenHornet/pull/592#issuecomment-1336243883).  
2:  Obsolete files used from KiCad 5 have been moved into the "Legacy" folder within each panel folder until deemed no longer needed.
3:  File structure has been reorganized and projects renamed to resemble OH nomenclature.
4:  Individual BOMs have been created for both Top and Bottom of each PCB.  This should help me feed information into the master BOM.

**Comment by jrsteensen** [comment]
Not a problem! Let me know when this is ready for full review and I'll block out some time. Thanks @Exprezz0 for all your hard work on this.

**Comment by Exprezz0** [comment]
Manufacturing files for all of the Backlit PCBs have been fixed.  Next step is to transition the ABSIS and Functional PCBs and create manufacturing files.

**Comment by Exprezz0** [comment]
Good news:  ABSIS Transition is now complete!  And even better news:  Huge step towards the master BOM being complete.  There are still a few things I ~~need~~ want to do inside the ABSIS directly like updating the 3d models and getting the images complete and STEPs recompiled.  But the transition itself is done and the manufacturing files have been updated.  I'll go back through and scrub everything one more time before calling it quits on the ABSIS folder.

I'll start work on the Functional PCBs (which I'm dreading due to all of the extra components)

**Comment by Exprezz0** [comment]
@jrsteensen  Transition complete.  I'm going to go back through and double check each PCB to get everything dress right dress, but you should be able to begin your review when you get the time.  Any commits from here, should be minor corrections.  

In the meantime, I'm going to finish working on the Master BOM, ReadMe, Installation, and Manufacturing.md

**Comment by jrsteensen** [comment]
If you could, I will begin the review, but I would like to have the Master BOM, README, Installation and Manufacturing files as part of this PR so it all gets merged together for ease of reference down the line on the repo. (And so I can validate those instructional documents as part of the review.)

**Comment by jrsteensen** [comment]
@Exprezz0 Do you have a list of issues this PR will close, referenced by issue number?

**Comment by Exprezz0** [comment]
@jrsteensen I have a break from work next week and I'll have all of those documents done by the weekend.  I was holding off on finishing them until we were comfortable there weren't any major issues that would void any documentation.  I needed to hit a checkpoint with the transition to keep from losing focus on the main purpose of the PR was.  

I do have a list of issues that I fixed, but I didn't reference any specific issue numbers.  When I catch a breather, I'll scrub through the issues and compare notes to see what I knocked out.  If anything, they're small fixes as I did my best to stay on track and not get carried away with the task at hand.

**Review by jrsteensen — CHANGES_REQUESTED** [review]
- [x] README.md: 
  - [ ] Word `labaled` should be `labeled` throughout.
  - [ ] Correct multiple spelling mistakes throughout document.
  - [ ] Add info about JLCPCB plugin.
- [x] MANUFACTURING.md
  - [ ] Correct spelling mistakes throughout. 
- [ ] File Structure
  - [ ] Move .step/.stp files to a `mcad` subfolder for each PCB
  - [ ] Move image files to a `media` subfolder for each PCB

### Individual PCB Reviews In Progress

**Comment by Exprezz0** [comment]
@jrsteensen All changes complete with last 3 commits ([ed94f74](https://github.com/jrsteensen/OpenHornet/pull/592/commits/ed94f7499be3d0e500d09b592ab19888c50e2521) [3512e76](https://github.com/jrsteensen/OpenHornet/pull/592/commits/3512e763f21021e5e372ff8f5a62d9f7cd7f7c9d) [31b25aa](https://github.com/jrsteensen/OpenHornet/pull/592/commits/31b25aad76061184ed3ba7c414f52c6f80daf290)) , per your last comment.

**Comment by Exprezz0** [comment]
* [ ] Model Review
  *  [ ] Link models to footprints
  *  [ ] Update .STEP and .PNGs
* [ ] Schematic update
* [ ] Drawing Sheet - link and update.
* [ ] Silkscreen update

**Comment by Exprezz0** [comment]
Gentle reminder:  Check interconnect to make sure nothing is using Pin D8/A8 as PWM on the ABSIS_ALE.  Silkscreen being revised to reflect.

**Comment by Exprezz0** [comment]
ABSIS_ATX Power Supply Unit is almost finished.  Just need to redo the production files once we figure out the proper resistor values.  This will also close #645

**Comment by Exprezz0** [comment]
PCB Review:  ABSIS is 99.962% Complete.  
The last thing left for ABSIS review is the proper resistor values for the ABSIS_ATX Power Supply Unit. 
- [ ] Update Value in Footrprint
- [ ] Update BOM and PCB Database with appropriate LSCS and manufacturing numbers
- [ ] Generate new Production Files
- [ ] Generate new STEP
- [ ] Generate new PNGs

**Review by Exprezz0 — COMMENTED** [review]
Moved Polarized Capacitor a tiny bit to give clearance for the Molex connector.  It was mounted on top of the capacitor pad.

**Comment by Exprezz0** [comment]
ABSIS Review is complete.
Backlight Panels is ~97.14% complete.  Just need to finish SEL JETT PANEL redesign based on F360 model modifications.

**Comment by Exprezz0** [comment]
Beginning KiCad 7 (current ver: 7.0.1) Transition:

1. ReadMe has been updated to reflect newest changes (primarily path related changes).  Should only affect those trying to contributing or using KiCad to view models.
2. 3d model, footprint, symbol library updates.
3. Correcting some overlooked errors when transition from KiCad 5 to 6.  (default clearances, copper pours)

**Comment by Exprezz0** [comment]
Huge update to all ECAD libraries:
Consolidated and reorganized Symbol library.  Renamed "Openhornet.kicad_sym" to "OH_Symbols" to match the rest of the naming convention.  Will continue to consolidate the rest of the symbols and update the metadata as I come across and use it.

ANT SEL Panel has been updated to support

Updated ANT SEL to support 3-way toggle switch:  4 LEDs added to backlight "AUTO" and "BOTH" text.  Made a few additional adjustments to PCB including adding TestPoints, adjusting tracks, etc.  Moving forward, backlight panels will use the Green 3.0mm LED instead of Red.  

And finally cleaned up and standardized the .schematic.  The schematic actually matches the PCB and is easy to read and now includes Manufacturer part numbers, LCSC part numbers, and datasheets.
 

- [ ] Still need to update and fix the F360 Back Plate model for the ANT SEL Panel based on the PCB Changes.  Recommend completely redoing the cut outs as LEDs slightly changed positions to make room for additional traces, capacitors, etc.
- [x] Thank @jrsteensen for all of his help and keeping me relatively sane through the process.  Thanks Noc!

**Comment by Exprezz0** [comment]
Tactical Pause.  Directory overhaul is nearing completion with just a few things left to do:

- [ ] ABSIS Transition to KiCad 7  (est: ~3hrs)
   - [ ] Change path of Drawing Sheet for schematic and PCB
   - [ ] Verify paths of symbols/footprints within schematic
   - [ ] Final review of manufacturing files and assets
- [ ] Backlight Panels - Type A (est: 2-3 days) - going alphabetically
   - [x] ANT SEL thru COMM 
   - [ ] DEFOG through SPIN RCV 
- [ ] Functional PCBs Transition to KiCad 7 (est: ~8-10hrs)
   - [ ] Change path of Drawing Sheet for schematic and PCB
   - [ ] Verify paths of symbols/footprints within schematic
   - [ ] Final review of manufacturing files and assets
- [ ] Fix any outstanding issues
- [ ] Final Review of Directory:   Check directory and ensure there are no duplicate, excess, or corrupted files.
- [ ] Update and Review Manufacturing.md and ReadMe.md
   - [ ] Add instructions for alternate parts as needed
- [ ] MasterBOM! (Requires everything else to be complete)

**Review by jrsteensen — APPROVED** [review]

**Pull request merged**
